# Generated by Django 4.1.3 on 2023-04-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djslug', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
